### ISSUE TITLE
Make cancellation asynchronous

### ISSUE THREAD

**Issue by jzila** [keybase/go-framed-msgpack-rpc#18]
Currently cancellation follows this workflow:

1. Client creates client context
2. Client makes a call request
3. RPC client creates a call and dispatches request across the wire
4. RPC server receives call.
5. RPC server creates a new context and saves it for retrieval
6. Client cancels client context
7. RPC client catches cancellation from context and dispatches a cancellation request across the wire
8. RPC server receives cancellation request, retrieves server context and cancels it
9. RPC protocol handler implementation handles the server context cancellation
10. RPC server sends the call response to the RPC client, which causes the client's (still blocked) call to return.

We want it to look like this:

1. ...
2. Client cancels client context
3. RPC client catches cancellation from context and immediately causes the client's call to return.
4. RPC client dispatches a cancellation request across the wire
4. RPC server receives cancellation request, retrieves server context and cancels it
5. RPC protocol handler implementation handles the server context cancellation and doesn't send a response.

**Comment by jzila** [comment]
Note: there is a race between dispatching a cancellation request to the server and the call responding. If this happens we just throw away the response.

**Comment by maxtaco** [comment]
In the current flow, when does the client's call return?

**Comment by jzila** [comment]
Step 10 in the first flow

**Comment by maxtaco** [comment]
Oh, I'm starting to get it.  Yeah, I agree the second is way better.
