### ISSUE TITLE
writerLoop should handle partial writes

### ISSUE THREAD

**Issue by akalin-keybase** [keybase/go-framed-msgpack-rpc#27]
In `writerLoop` in `transport.go`, we call `cdec.Write` and use only the err, which is always non-nil if the write is partial. However, this does the wrong thing -- we don't want to return the error and fail the RPC call (I think), but instead we just want to write the remainder of the data.

I may be missing something, though -- I'm surprised we haven't run into this with, say, large block writes.

**Comment by jzila** [comment]
The trouble is we don't know what "remainder of the data" means. If we tried to write an argument (which I assume is how we're sending blocks), then all we can do if it fails is to send the argument again.

**Comment by akalin-keybase** [comment]
But Write returns how many bytes it has written -- we're currently just throwing it away, but we can just compare that to how many bytes we wanted to write and call Write again with the appropriate slice, repeating until bytes remaining == 0.

**Comment by jzila** [comment]
We'd have to figure out the delta and not resend data, otherwise the receiver would fail because it'd receive the same data multiple times.

**Comment by akalin-keybase** [comment]
Perhaps I'm not being clear -- we can indeed figure out the delta. This is what I mean. Instead of:

```
_, err := conn.Write(data)
// check err
```
do
```
for len(data) > 0 {
  written, err := conn.Write(data)
  // check err
  data = data[written:]
}
```

**Comment by jzila** [comment]
Oh I understand now, sorry, it's late.

**Comment by maxtaco** [comment]
According to the [Go docs](https://golang.org/pkg/io/#Writer), writers should only report short writes if there was an error.

**Comment by maxtaco** [comment]
Is this a bug in the underlying connection?

**Comment by jzila** [comment]
I don't think so; @akalin-keybase is saying that we should handle the partial write case better than just terminating the transport.

**Comment by jzila** [comment]
Do we have consensus on this? Seems like something that's simple enough to do.

**Comment by akalin-keybase** [comment]
Sorry, @maxtaco is right -- I was reading the docs wrong! There's no need to wrap this in a loop -- Write will only return if there's a fatal error (it does the loop for partial writes internally).
