### ISSUE TITLE
Need to ignore new fields for backwards compatibility

### ISSUE THREAD

**Issue by akalin-keybase** [keybase/go-framed-msgpack-rpc#44]
This is required before we roll out any changes that adds new fields, i.e. debug tags.

**Comment by akalin-keybase** [comment]
@max's proposal:

v1: is what we have
​[11:59 AM] 
v2: is a version that takes n+ fields, and has debug tags, but leaves debug tags empty if not specified
​[11:59 AM] 
v3: is version that takes n+ fields, has debug tags, and doesn’t leave debug tags empty if not specified
​[12:00 PM] 
we can run v1 and v2 against each other
​[12:00 PM] 
we can’t run v3 against v1

**Comment by jzila** [comment]
Fixed in #50
