### ISSUE TITLE
Investigate server hang persisting after client disconnection

### ISSUE THREAD

**Issue by akalin-keybase** [keybase/go-framed-msgpack-rpc#45]
Per @maxtaco 

@jzila / @akalin  I had one more thought
​[9:40 PM] 
in the logging deadlock, why didn’t killing the client clear the deadlock?
​[9:41 PM] 
my guess is that outstanding calls aren’t be cleared when the underlying connection dies
​[9:41 PM] 
maybe that’s a new regression that caused this bug to be as bad as it was

**Comment by akalin-keybase** [comment]
To expand on what @maxtaco said, he's asking why killing the locked client clear the deadlock on the server.

I looked a little bit into this. I don't actually see a deadlock on a client, even if it caused the corresponding server connection to deadlock also, could affect other connections. The RPC library doesn't handle the Accept() -- you create a new Transport only when you already have a net.Conn from Accept, so unless there's some shared global state, I don't see how clients can affect each other.

Thinking back, I'm not actually sure the server was deadlocked at all. The symptom was that any keybase command would lock up, but that could easily be explained by each keybase operation immediately running into the deadlock, and not necessarily the server locking up, too. @maxtaco do you remember anything that pointed towards the server locking up?

**Comment by maxtaco** [comment]
The deadlock was a few levels up in application logic.  There is the
keybase service and CLI.  The service holds a lock as it synchronously
calls an RPC on the CLI. The CLI, in servicing this RPC calls to the
service and the first thing the service does is to try to grab the lock in
step 1.

Now the service is locked up. Any subsequent calls to the service need that
lock (it protects logging) so they are lock up asap.

So no bug in the rpc library yet. But when I kill the CLI I would expect
the service to see and EOF and to flush out any outstanding RPC to the CLI
with an error code.  So I would expect the synchronous call in step 1 to
error out and for the service to release its lock on its way out of that
function (I can fill in names later).  But this didnt seem to happen. Or
maybe it did but the service wound up in deadlock immediately after for the
same reason.

**Comment by jzila** [comment]
This appears fixed, likely as a result of the fix for #47
